import { redirect } from 'next/dist/server/api-utils'
import Head from 'next/head'

export function getServerSideProps() {
  return {
    redirect: {
      permanent: false,
      destination: '/home'
    },
    props: {}
  }
}

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>typeNotes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
